### ISSUE TITLE
can now only run your client

### ISSUE THREAD

**Issue by energizer60** [dalovar/league-of-legends-voice-chat-on-mac#1]
Hi. I tried your script, but now when I press the league icon, I get your app every time :(

**Comment by nixtoshi** [comment]
My app is designed to launch League's client, running League's client directly should only open League's client directly (and not my app). Also I think you no longer need my app to make League's voice chat work on mac. They seem to have fixed the issue with World's patch (9.19), I no longer see the issue being listed here: https://status.leagueoflegends.com/#na
I haven't tried myself as I no longer play on my mac and don't have the game installed. Let me know if just running the game alone works!
