### ISSUE TITLE
LoL broken atfer installation

### ISSUE THREAD

**Issue by madnarroo** [dalovar/league-of-legends-voice-chat-on-mac#2]
Hello, 

I downloaded and ran your app before opening LoL.

1) I didn't get the thing asking for permission
2) The LoL client kept disconnecting from the internet

What is the issue ?

**Comment by madnarroo** [comment]
Is there a way to remove your app ?

I think it might be creating issues with the client

I even deleted LoL and re-installed it but it keeps on crashing when I click on play

**Comment by nixtoshi** [comment]
Hey @madnarroo

This app is just a launcher that opens the official League client on its own, and cares about asking for the right permissions.

It won't do anything else so it shouldn't cause any issue, doesn't change or move any files at all, so you can just delete it and you are back where you started.

To make it work:
When using this app, only use my launcher to run the game and follow the instructions written on the main page of this repository. If you run the official game client directly, you will be able to play normally but without microphone access. So every time you want the microphone enabled you have to run my launcher. You only need to enable enable the microphone permissions once.

 At some point League may fix their client, and you will have microphone access wether you open my launcher or theirs.

**Comment by madnarroo** [comment]
Hello again,

It might have been another issue.

I tried again, and the app works perfectly !

Thanks a lot !

**Comment by nixtoshi** [comment]
Awesome, feel free to buy me a pizza:
http://paypal.me/daxlo
😄
