### ISSUE TITLE
Not working for a week in MacOS Big Sur 11.x

### ISSUE THREAD

**Issue by BkMiguel12** [dalovar/league-of-legends-voice-chat-on-mac#3]
Hello bro !
I downloaded your little app but it doesn't work for me, I can't connect to league voice.

Does this method still work for you?

The microphone test all good, I can speak and recognize it. But I can't connect to the league voice

**Comment by nixtoshi** [comment]
My app is working fine, not sure what this new bug is. Seems to be a new bug introduced with the MSI update, where mac users can't connect to League voice at all.

Sorry, but I'd recommend you and your friends use Discord for now until Riot fixes this new bug. My app only solves a permission issue with Mac, which is how a lot of Mac users were able to use League Voice up until this latest MSI update

**Comment by nixtoshi** [comment]
Closing this, since the app is back at work!
