### ISSUE TITLE
Permabanned

### ISSUE THREAD

**Issue by Ralphchahwan** [dalovar/league-of-legends-voice-chat-on-mac#4]
Whomever is reading this
Do not use this software, I just got a message that I was permanently banned from LoL for using Third Party Software

**Comment by nixtoshi** [comment]
Contact LoL.

Me and thousands of users have been using this fix without issue. This software doesn't modify the game or affect it in any way, it just launches the game with the right permissions enabled.

They probably made a mistake, or your account was actually hacked/misused by someone else (which happened to me once, and it got re-enabled).
