### ISSUE TITLE
Different Application Path?

### ISSUE THREAD

**Issue by kashanico** [dalovar/league-of-legends-voice-chat-on-mac#6]
Hi there,
Is there a way to modify this to point to a different install location for the LoL? 
I have mine installed on Users\name\Applications to have it be installed only for a specific user.

**Comment by nixtoshi** [comment]
Yes, make a new MacOS app on mac's Automator.app.

Create a "Run Shell Script task" and paste this code:

```
# Goes into the app's contents
cd '/Applications/League of Legends.app/Contents/LoL/'
# Runs the client
./LeagueClient.app/Contents/MacOS/LeagueClient
# Kills the script monitor that makes de the cog icon from the Automator task show
killAll ScriptMonitor
```

Modify path after `cd` to be whatever path you want and test that app. If it works save it, and use it instead of the LoL launcher
