### ISSUE TITLE
League client crashes and cannot test microphone

### ISSUE THREAD

**Issue by steventran334** [dalovar/league-of-legends-voice-chat-on-mac#8]
Hi all, 

Tried downloading this on my M1 Pro running venture 13.0.1 and can't seem to get it working. Is it just that this isn't updated for my OS?

**Comment by nixtoshi** [comment]
Possible, never upgraded to M1. Many seem to use it without issue on other macs.

This problem has been going on for almost half a decade on Mac without much response from LoL.

I would recommend that you use **Discord** for voice instead.

If Discord causes a higher ping (it usually does), use it through a mobile hotspot or a different internet connection.
